// predefinedColorLayouts.js

export const predefinedColorLayouts = {
    "Classic Purple": {
        primary: "#8A4D76",
        secondary: "#F5A623",
        link: "#FA7C91",
        text: "#363636",
        heading: "#1A1A1A",
        background: "#ffffff",
        muted: "#7A7A7A",
        success: "#48C774",
        warning: "#FFDD57",
        danger: "#F14668",
        info: "#209CEE",
        border: "#DBDBDB",
        hover: "#f2f2f2",
        navbarBackground: "#ffffff",
        navbarText: "#363636",
        footerBackground: "#F8F8F8",
        footerText: "#363636",
        sidebarBackground: "#FAFAFA",
        sidebarText: "#363636",
        cardBackground: "#FFFFFF",
        cardHeaderBackground: "#F5F5F5",
        cardText: "#363636",
        buttonBackground: "#8A4D76",
        buttonText: "#FFFFFF",
        inputBackground: "#FFFFFF",
        inputBorder: "#DBDBDB",
        inputText: "#363636",
        inputPlaceholder: "#AAAAAA",
        modalBackground: "#FFFFFF",
        modalOverlay: "rgba(0,0,0,0.5)",
        highlight: "#FFF3B0",
        linkHover: "#FF9AA2",
        shadow: "rgba(0,0,0,0.1)"
    },

    "Ocean Blue": {
        primary: "#1E90FF",
        secondary: "#00CED1",
        link: "#00BFFF",
        text: "#2F4F4F",
        heading: "#1C1C1C",
        background: "#F0F8FF",
        muted: "#708090",
        success: "#48C774",
        warning: "#FFD700",
        danger: "#DC143C",
        info: "#1E90FF",
        border: "#B0C4DE",
        hover: "#E0FFFF",
        navbarBackground: "#E6F7FF",
        navbarText: "#1C1C1C",
        footerBackground: "#B0E0E6",
        footerText: "#1C1C1C",
        sidebarBackground: "#F0FFFF",
        sidebarText: "#2F4F4F",
        cardBackground: "#FFFFFF",
        cardHeaderBackground: "#B0E0E6",
        cardText: "#2F4F4F",
        buttonBackground: "#1E90FF",
        buttonText: "#FFFFFF",
        inputBackground: "#FFFFFF",
        inputBorder: "#B0C4DE",
        inputText: "#2F4F4F",
        inputPlaceholder: "#A9A9A9",
        modalBackground: "#FFFFFF",
        modalOverlay: "rgba(0,0,0,0.5)",
        highlight: "#B0E0E6",
        linkHover: "#00CED1",
        shadow: "rgba(0,0,0,0.15)"
    },

    "Sunset Glow": {
        primary: "#FF6F61",
        secondary: "#FFD700",
        link: "#FF8C00",
        text: "#3D2B1F",
        heading: "#2C1A0D",
        background: "#FFF5E1",
        muted: "#A0522D",
        success: "#48C774",
        warning: "#FFA500",
        danger: "#F14668",
        info: "#FF6347",
        border: "#E0C097",
        hover: "#FFE4B5",
        navbarBackground: "#FFDAB9",
        navbarText: "#3D2B1F",
        footerBackground: "#FFE4B5",
        footerText: "#3D2B1F",
        sidebarBackground: "#FFF8DC",
        sidebarText: "#3D2B1F",
        cardBackground: "#FFFFFF",
        cardHeaderBackground: "#FFEBCD",
        cardText: "#3D2B1F",
        buttonBackground: "#FF6F61",
        buttonText: "#FFFFFF",
        inputBackground: "#FFFFFF",
        inputBorder: "#E0C097",
        inputText: "#3D2B1F",
        inputPlaceholder: "#A0522D",
        modalBackground: "#FFFFFF",
        modalOverlay: "rgba(0,0,0,0.5)",
        highlight: "#FFDAB9",
        linkHover: "#FF8C00",
        shadow: "rgba(0,0,0,0.2)"
    }
};
