export const predefinedColorLayouts = {
    "Classic Purple": {
        primary: "#8A4D76",
        secondary: "#F5A623",
        link: "#FA7C91",
        text: "#363636",
        heading: "#1A1A1A",
        background: "#ffffff",
        muted: "#7A7A7A",
        success: "#48C774",
        warning: "#FFDD57",
        danger: "#F14668",
        info: "#209CEE",
        border: "#DBDBDB",
        hover: "#f2f2f2",
        "navbar-background": "#8A4D76",
        "navbar-text": "#FFFFFF",
        "footer-background": "#F8F8F8",
        "footer-text": "#363636",
        "sidebar-background": "#FAFAFA",
        "sidebar-text": "#363636",
        "card-background": "#FFFFFF",
        "card-header-background": "#F5F5F5",
        "card-text": "#363636",
        "button-background": "#8A4D76",
        "button-text": "#FFFFFF",
        "input-background": "#FFFFFF",
        "input-border": "#DBDBDB",
        "input-text": "#363636",
        "input-placeholder": "#AAAAAA",
        "modal-background": "#FFFFFF",
        "modal-overlay": "rgba(0,0,0,0.5)",
        highlight: "#FFF3B0",
        "link-hover": "#FF9AA2",
        shadow: "rgba(0,0,0,0.1)"
    },

    "Ocean Blue": {
        primary: "#1E90FF",
        secondary: "#00CED1",
        link: "#00BFFF",
        text: "#2F4F4F",
        heading: "#1C1C1C",
        background: "#F0F8FF",
        muted: "#708090",
        success: "#48C774",
        warning: "#FFD700",
        danger: "#DC143C",
        info: "#1E90FF",
        border: "#B0C4DE",
        hover: "#E0FFFF",
        "navbar-background": "#0077B6", // darker, richer navbar
        "navbar-text": "#FFFFFF",
        "footer-background": "#B0E0E6",
        "footer-text": "#1C1C1C",
        "sidebar-background": "#F0FFFF",
        "sidebar-text": "#2F4F4F",
        "card-background": "#FFFFFF",
        "card-header-background": "#B0E0E6",
        "card-text": "#2F4F4F",
        "button-background": "#1E90FF",
        "button-text": "#FFFFFF",
        "input-background": "#FFFFFF",
        "input-border": "#B0C4DE",
        "input-text": "#2F4F4F",
        "input-placeholder": "#A9A9A9",
        "modal-background": "#FFFFFF",
        "modal-overlay": "rgba(0,0,0,0.5)",
        highlight: "#B0E0E6",
        "link-hover": "#00CED1",
        shadow: "rgba(0,0,0,0.15)"
    },

    "Sunset Glow": {
        primary: "#FF6F61",
        secondary: "#FFD700",
        link: "#FF8C00",
        text: "#3D2B1F",
        heading: "#2C1A0D",
        background: "#FFF5E1",
        muted: "#A0522D",
        success: "#48C774",
        warning: "#FFA500",
        danger: "#F14668",
        info: "#FF6347",
        border: "#E0C097",
        hover: "#FFE4B5",
        "navbar-background": "#FF8C42",
        "navbar-text": "#FFFFFF",
        "footer-background": "#FFE4B5",
        "footer-text": "#3D2B1F",
        "sidebar-background": "#FFF8DC",
        "sidebar-text": "#3D2B1F",
        "card-background": "#FFFFFF",
        "card-header-background": "#FFEBCD",
        "card-text": "#3D2B1F",
        "button-background": "#FF6F61",
        "button-text": "#FFFFFF",
        "input-background": "#FFFFFF",
        "input-border": "#E0C097",
        "input-text": "#3D2B1F",
        "input-placeholder": "#A0522D",
        "modal-background": "#FFFFFF",
        "modal-overlay": "rgba(0,0,0,0.5)",
        highlight: "#FFDAB9",
        "link-hover": "#FF8C00",
        shadow: "rgba(0,0,0,0.2)"
    },

    "Forest Mist": {
        primary: "#2E8B57",
        secondary: "#A9DFBF",
        link: "#3CB371",
        text: "#2F4F4F",
        heading: "#1C3B2E",
        background: "#E6F2EA",
        muted: "#708090",
        success: "#48C774",
        warning: "#FFD700",
        danger: "#DC143C",
        info: "#20B2AA",
        border: "#C1E1C1",
        hover: "#D0F0C0",
        "navbar-background": "#2E8B57",
        "navbar-text": "#FFFFFF",
        "footer-background": "#A9DFBF",
        "footer-text": "#2F4F4F",
        "sidebar-background": "#DFF0D8",
        "sidebar-text": "#2F4F4F",
        "card-background": "#FFFFFF",
        "card-header-background": "#A9DFBF",
        "card-text": "#2F4F4F",
        "button-background": "#2E8B57",
        "button-text": "#FFFFFF",
        "input-background": "#FFFFFF",
        "input-border": "#C1E1C1",
        "input-text": "#2F4F4F",
        "input-placeholder": "#A9A9A9",
        "modal-background": "#FFFFFF",
        "modal-overlay": "rgba(0,0,0,0.5)",
        highlight: "#D0F0C0",
        "link-hover": "#3CB371",
        shadow: "rgba(0,0,0,0.15)"
    },

    "Candy Pop": {
        primary: "#FF4EC1",
        secondary: "#FFB6C1",
        link: "#FF69B4",
        text: "#4A2C2A",
        heading: "#3B1F2F",
        background: "#FFF0F5",
        muted: "#A0522D",
        success: "#48C774",
        warning: "#FFD700",
        danger: "#F14668",
        info: "#FF69B4",
        border: "#F0C0D0",
        hover: "#FFE0F0",
        "navbar-background": "#FF69B4",
        "navbar-text": "#FFFFFF",
        "footer-background": "#FFC0CB",
        "footer-text": "#4A2C2A",
        "sidebar-background": "#FFE4E1",
        "sidebar-text": "#4A2C2A",
        "card-background": "#FFFFFF",
        "card-header-background": "#FFC0CB",
        "card-text": "#4A2C2A",
        "button-background": "#FF4EC1",
        "button-text": "#FFFFFF",
        "input-background": "#FFFFFF",
        "input-border": "#F0C0D0",
        "input-text": "#4A2C2A",
        "input-placeholder": "#A0522D",
        "modal-background": "#FFFFFF",
        "modal-overlay": "rgba(0,0,0,0.5)",
        highlight: "#FFE0F0",
        "link-hover": "#FF4EC1",
        shadow: "rgba(0,0,0,0.2)"
    },

    "Sunrise Citrus": {
        primary: "#FF9505",
        secondary: "#FFD700",
        link: "#FF7F50",
        text: "#3D2B1F",
        heading: "#2C1A0D",
        background: "#FFF8E7",
        muted: "#A0522D",
        success: "#48C774",
        warning: "#FFA500",
        danger: "#F14668",
        info: "#FF6347",
        border: "#E0C097",
        hover: "#FFF0CC",
        "navbar-background": "#FF9505",
        "navbar-text": "#FFFFFF",
        "footer-background": "#FFE4B5",
        "footer-text": "#3D2B1F",
        "sidebar-background": "#FFF5CC",
        "sidebar-text": "#3D2B1F",
        "card-background": "#FFFFFF",
        "card-header-background": "#FFD580",
        "card-text": "#3D2B1F",
        "button-background": "#FF9505",
        "button-text": "#FFFFFF",
        "input-background": "#FFFFFF",
        "input-border": "#E0C097",
        "input-text": "#3D2B1F",
        "input-placeholder": "#A0522D",
        "modal-background": "#FFFFFF",
        "modal-overlay": "rgba(0,0,0,0.5)",
        highlight: "#FFF0CC",
        "link-hover": "#FF7F50",
        shadow: "rgba(0,0,0,0.2)"
    },

    /**
     * "Mint Breeze" – Light, airy, modern
     * Soft greens and blues, excellent for wellness or fintech layouts
     */
    "Mint Breeze": {
        primary: "#3EB489",       // soft mint green
        secondary: "#A3E7D1",     // pastel aqua
        link: "#2D8F6B",          // darker mint for links
        text: "#1B1B1B",          // dark text for readability
        heading: "#0D3B2E",       // strong contrast headings
        background: "#F0FFF9",    // soft off-white
        muted: "#7D7D7D",
        success: "#48C774",
        warning: "#FFD57F",
        danger: "#F14668",
        info: "#2D8F6B",
        border: "#D9F0EB",
        hover: "#E0FAF2",
        "navbar-background": "#3EB489",
        "navbar-text": "#FFFFFF",
        "footer-background": "#A3E7D1",
        "footer-text": "#1B1B1B",
        "sidebar-background": "#E0FAF2",
        "sidebar-text": "#1B1B1B",
        "card-background": "#FFFFFF",
        "card-header-background": "#A3E7D1",
        "card-text": "#1B1B1B",
        "button-background": "#3EB489",
        "button-text": "#FFFFFF",
        "input-background": "#FFFFFF",
        "input-border": "#D9F0EB",
        "input-text": "#1B1B1B",
        "input-placeholder": "#AAAAAA",
        "modal-background": "#FFFFFF",
        "modal-overlay": "rgba(0,0,0,0.4)",
        highlight: "#A3E7D1",
        "link-hover": "#2D8F6B",
        shadow: "rgba(0,0,0,0.1)"
    },

    /**
     * "Solar Flare" – High energy, dramatic contrast
     * Great for marketing sites or call-to-action heavy layouts
     */
    "Solar Flare": {
        primary: "#FF4500",       // blazing orange
        secondary: "#FFD700",     // golden accent
        link: "#FF6347",          // tomato red for links
        text: "#1A1A1A",
        heading: "#0D0D0D",
        background: "#FFF8F0",
        muted: "#7A7A7A",
        success: "#f77373ff",
        warning: "#FFA500",
        danger: "#FF2400",
        info: "#FF6347",
        border: "#F5D6A1",
        hover: "#D11F00",
        "info-hover": "#2f0929ff",
        "navbar-background": "#FF4500",
        "navbar-text": "#FFFFFF",
        "footer-background": "#FFD700",
        "footer-text": "#1A1A1A",
        "sidebar-background": "#FFF0E0",
        "sidebar-text": "#1A1A1A",
        "card-background": "#FFFFFF",
        "card-header-background": "#FF6347",
        "card-text": "#1A1A1A",
        "button-background": "#FF4500",
        "button-text": "#FFFFFF",
        "input-background": "#FFFFFF",
        "input-border": "#F5D6A1",
        "input-text": "#1A1A1A",
        "input-placeholder": "#AAAAAA",
        "modal-background": "#FFFFFF",
        "modal-overlay": "rgba(0,0,0,0.5)",
        highlight: "#FFE5CC",
        "link-hover": "#FF6347",
        shadow: "rgba(0,0,0,0.2)"
    }
};
